const {chromium}=require('/Users/imac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[],remote=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});
 await page.goto('file://'+path.resolve(__dirname,'../index.html'));await page.click('#studioDemo');await page.waitForTimeout(600);
 assert.match(await page.locator('#studioResult').innerText(),/422.0037 mAU·mL/);
 await page.evaluate(()=>Plotly.relayout('plotlyChart',{'xaxis.range':[9,15]}));await page.waitForTimeout(500);
 const zoom=await page.evaluate(()=>({range:el('plotlyChart').layout.xaxis.range,shapes:el('plotlyChart').layout.shapes.filter(s=>s.type==='rect').map(s=>[s.x0,s.x1,s.xref]),labels:el('plotlyChart').layout.annotations.filter(a=>a.text==='A10').length}));
 assert.deepEqual(zoom.range,[9,15]);assert(zoom.shapes.every(s=>s[0]>=9&&s[1]<=15&&s[2]==='x'));assert(zoom.labels>0);
 const before=await page.locator('#integStartValue').inputValue();
 const boundary=await page.locator('.boundary-handle').first().boundingBox();
 await page.mouse.move(boundary.x+7,boundary.y+boundary.height/2);await page.mouse.down();await page.mouse.move(boundary.x+25,boundary.y+boundary.height/2,{steps:8});await page.mouse.up();await page.waitForTimeout(500);
 const after=await page.locator('#integStartValue').inputValue();assert.notEqual(before,after,'actual mouse drag must update boundary input');
 await page.click('#studioKeep');assert.match(await page.locator('#studioPeaks').innerText(),/100.0/);
 const csvWait=page.waitForEvent('download');await page.click('#studioCSV');const csv=await csvWait;await csv.saveAs(path.resolve(__dirname,'../test-peaks.csv'));
 const svgWait=page.waitForEvent('download');await page.click('#studioSVG');const svg=await svgWait;await svg.saveAs(path.resolve(__dirname,'../test-export.svg'));
 await page.evaluate(()=>processAktaFile([['Chrom.1'],['UV','','Fraction',''],['CV','mAU','CV','Fraction'],['0','1','0','A1'],['1','','1','A2'],['2','3','2','A3'],['3','2','','']]));await page.waitForTimeout(500);
 const imported=await page.evaluate(()=>({x:rawData.UV.x,y:rawData.UV.y,unit:xUnit()}));assert.deepEqual(imported,{x:[0,2,3],y:[1,3,2],unit:'CV'});

 await page.click('#studioDemo');await page.waitForTimeout(500);
 const base=await page.evaluate(()=>({end:rawData.UV.x.at(-1),fraction:fractionData[0].position,start:Number(el('integStartValue').value),area:v6Result().net}));
 await page.selectOption('#studioUnit','CV');assert.match(await page.locator('#studioConversionHint').innerText(),/大于 0/);assert.equal(await page.locator('#studioUnit').inputValue(),'');
 await page.fill('#studioColumnVolume','24');await page.locator('#studioColumnVolume').blur();await page.selectOption('#studioUnit','CV');await page.waitForTimeout(300);
 const cv=await page.evaluate(()=>({end:rawData.UV.x.at(-1),fraction:fractionData[0].position,start:Number(el('integStartValue').value),area:v6Result().net,original:originalRawData.UV.x.at(-1)}));
 assert.equal(cv.end,1);assert.equal(cv.fraction,.25);assert(Math.abs(cv.start-base.start/24)<1e-12);assert(Math.abs(cv.area-base.area/24)<1e-9);assert.equal(cv.original,24);
 await page.click('#studioKeep');
 await page.fill('#studioColumnVolume','12');await page.locator('#studioColumnVolume').blur();await page.waitForTimeout(300);
 assert.equal(await page.evaluate(()=>rawData.UV.x.at(-1)),2);assert.match(await page.locator('#studioPeaks').innerText(),/mAU·CV/);
 const sessionWait=page.waitForEvent('download');await page.click('#saveSessionBtn');const session=await sessionWait;const sessionPath=path.resolve(__dirname,'../test-session.json');await session.saveAs(sessionPath);
 await page.click('#studioDemo');await page.waitForTimeout(300);
 await page.locator('input[onchange="loadSession(event)"]').setInputFiles(sessionPath);await page.waitForTimeout(500);
 assert.equal(await page.locator('#studioColumnVolume').inputValue(),'12');assert.equal(await page.evaluate(()=>rawData.UV.x.at(-1)),2);assert.equal(await page.evaluate(()=>xUnit()),'CV');assert.match(await page.locator('#studioPeaks').innerText(),/mAU·CV/);
 await page.selectOption('#studioUnit','mL');await page.waitForTimeout(300);
 const back=await page.evaluate(()=>({end:rawData.UV.x.at(-1),area:v6Result().net,fraction:fractionData[0].position}));assert.equal(back.end,24);assert.equal(back.fraction,6);assert(Math.abs(back.area-base.area)<1e-9);
 await page.fill('#studioColumnVolume','0');await page.locator('#studioColumnVolume').blur();assert.equal(await page.locator('#studioColumnVolume').inputValue(),'12');

 await page.click('#studioDemo');await page.waitForTimeout(400);
 await page.click('button[onclick*="switchTab(\'analysis\'"]');
 await page.selectOption('#tubeRangeMode','fraction');await page.selectOption('#tubeEnd','8');await page.selectOption('#tubeStart','5');await page.waitForTimeout(300);
 assert.equal(await page.locator('#integStartValue').inputValue(),'8');assert.equal(await page.locator('#integEndValue').inputValue(),'10');
 assert.match(await page.locator('#tubeRangeHint').innerText(),/A5 开始 → A8 结束/);
 assert.equal(await page.locator('.boundary-handle').count(),0);
 const tubeArea=await page.evaluate(()=>v6Result().net);
 const expectedTubeArea=await page.evaluate(()=>ChromCore.integrate(rawData.UV,8,10,'linear',0).net);assert.equal(tubeArea,expectedTubeArea);
 await page.fill('#studioColumnVolume','24');await page.locator('#studioColumnVolume').blur();await page.selectOption('#studioUnit','CV');await page.waitForTimeout(200);
 assert(Math.abs(Number(await page.locator('#integEndValue').inputValue())-10/24)<1e-12);
 assert(Math.abs(await page.evaluate(()=>v6Result().net)-tubeArea/24)<1e-9);
 const tubeSave=page.waitForEvent('download');await page.evaluate(()=>saveSession());const tubeSession=await tubeSave;const tubePath=path.resolve(__dirname,'../test-tube-session.json');await tubeSession.saveAs(tubePath);
 await page.click('#studioDemo');await page.locator('#loadSessionInput').setInputFiles(tubePath);await page.waitForTimeout(400);
 assert.equal(await page.locator('#tubeRangeMode').inputValue(),'fraction');assert.equal(await page.locator('#tubeStart').inputValue(),'5');assert.equal(await page.locator('#tubeEnd').inputValue(),'8');
 await page.selectOption('#tubeEnd','33');assert.match(await page.locator('#studioResult').innerText(),/终点未知/);assert.equal(await page.locator('#integEndValue').inputValue(),'');
 await page.selectOption('#tubeEnd','8');await page.selectOption('#tubeRangeMode','coordinate');assert.equal(await page.locator('#integStartValue').getAttribute('readonly'),null);
 await page.click('#studioDemo');await page.waitForTimeout(500);await page.screenshot({path:path.resolve(__dirname,'../preview.png'),fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);console.log('PASS: offline render, zoom alignment, sparse labels, mouse drag, multi-peak table, CSV, SVG, missing-Y import, CV unit; CV conversion, volume edits, session roundtrip, tube 5–8 inclusive range, tube mode restore, unknown endpoint rejection; no JS errors / remote requests');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
